name: sim_service
description: A new flutter plugin project for getting sim data service *this plugin runs with android for now *.
version: 0.0.1
author: "cloudsoft<osama@cloudsoft.com>"
homepage: https://github.com/osamagamal65

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.cloudsoft.simservice
    pluginClass: SimServicePlugin
environment:
  sdk: ">=2.1.0 <3.0.0"
